### ISSUE TITLE
astar_minvo.m errors

### ISSUE THREAD

**Issue by FahadTan** [mit-acl/minvo#2]
Running in MATLAB2020a and MATLAB 2018b. Used the recommended and also recent version of YALMIP.

Errors in executing the following line of code:

constraints=[V_MV==(Vbs_first_block*Mvel_bs2basis(1:2,1:3)+V3_Bs*Mvel_bs2basis(3,1:3))];

Error using sdpvar/sym (line 97)
Error: Invalid expression. Check for missing multiplication operator, missing or unbalanced delimiters, or other syntax error. To
construct matrices, use brackets instead of parentheses.

Error in sym/privResolveArgs (line 1005)
                    argout{k} = sym(arg);

Error in sym/privBinaryOp (line 1029)
            args = privResolveArgs(A, B);

Error in  +  (line 7)
X = privBinaryOp(A, B, 'symobj::zipWithImplicitExpansion', '_plus');

Error in astar_minvo>getChildrenOfQ (line 84)
    constraints=[V_MV==(Vbs_first_block*Mvel_bs2basis(1:2,1:3)+V3_Bs*double(Mvel_bs2basis(3,1:3)))];

Error in astar_minvo (line 21)
qiP1_samples= getChildrenOfQ(Q);

**Comment by jtorde** [comment]
Please checkout the last commit I have just pushed, this should be solved there

I'm closing this issue for now, but feel free to open it if you are still finding this issue
